baseURL = "https://shrlab.com/"
languageCode = "us"
title = "Sams Sporadic Segments"
relativeURLs = true
theme = ["https://github.com/theNewDynamic/gohugo-theme-ananke"]


enableGitInfo = true

# disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "RSS","JSON"]
