baseURL = "https://shrlab.com/"
languageCode = "us"
title = "Sams Sporadic Segments"
relativeURLs = true

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'
